# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

development:
  api_key: a9b0a10d0cfaf5b10cf3dbae690e7421
  secret_key: 99727a9417403312e70bdb5343f7af7a
  canvas_page_name: racemenu_staging
  callback_url: http://www.staging.racemenu.com
  pretty_errors: false
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: tunnlr800
    public_host: ssh1.tunnlr.com
    public_port: 10535
    local_port: 3000

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

production:
  api_key: 32faece01d59996522f4702ebad0f2f7
  secret_key: a4b0a98370ad6cae31ba49238128da50
  canvas_page_name: 
  callback_url: 
  set_asset_host_to_callback_url: true   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
